name: Test Suite

on:
  push:
    branches: [ main, develop, feature/*, bugfix/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: course_tutor_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and test
      run: |
        # Build the application
        docker compose build
        
        # Create test database and run migrations
        docker run --rm -e DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/course_tutor_test -e RAILS_ENV=test course_tutor_app-web rails db:create
        docker run --rm -e DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/course_tutor_test -e RAILS_ENV=test course_tutor_app-web rails db:migrate
        
        # Run tests
        docker run --rm -e DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/course_tutor_test -e RAILS_ENV=test course_tutor_app-web bundle exec rspec

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: spec/examples.txt
        retention-days: 7 